steps:
  # Extract repository and commit information
  - name: 'gcr.io/cloud-builders/git'
    id: 'extract-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get repository information
        REPO_NAME=$REPO_NAME
        BRANCH_NAME=$BRANCH_NAME
        COMMIT_SHA=$COMMIT_SHA
        PROJECT_ID=$PROJECT_ID
        
        # Get commit details using git commands
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")
        AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
        AUTHOR_EMAIL=$(git log -1 --pretty=format:"%ae")
        
        # Get modified files
        ADDED_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA --diff-filter=A | jq -R -s -c 'split("\n")[:-1]' || echo "[]")
        MODIFIED_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA --diff-filter=M | jq -R -s -c 'split("\n")[:-1]' || echo "[]")
        REMOVED_FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA --diff-filter=D | jq -R -s -c 'split("\n")[:-1]' || echo "[]")
        
        echo "Repository: $REPO_NAME"
        echo "Branch: $BRANCH_NAME"
        echo "Commit: $COMMIT_SHA"
        echo "Author: $AUTHOR_NAME"
        
        # Create JSON payload
        cat > /workspace/event.json << EOF
        {
          "repository": {
            "name": "$$REPO_NAME",
            "full_name": "$$PROJECT_ID/$$REPO_NAME"
          },
          "ref": "refs/heads/$$BRANCH_NAME",
          "pusher": {
            "name": "$$AUTHOR_NAME",
            "email": "$$AUTHOR_EMAIL"
          },
          "commits": [
            {
              "id": "$$COMMIT_SHA",
              "message": "$$COMMIT_MSG",
              "author": {
                "name": "$$AUTHOR_NAME",
                "email": "$$AUTHOR_EMAIL"
              },
              "added": $$ADDED_FILES,
              "modified": $$MODIFIED_FILES,
              "removed": $$REMOVED_FILES
            }
          ]
        }
        EOF

        
        # Print the event data for debugging
        cat /workspace/event.json

  # Publish event to Pub/Sub
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'publish-event'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Publish the event to Pub/Sub
        gcloud pubsub topics publish github-events --message-body="$(cat /workspace/event.json)"
        echo "Published event to github-events topic"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '600s'
